#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EldYoungAndroidApp.Resource", IsApplication=true)]

namespace EldYoungAndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int bottomin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int bottomout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int fade_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int fade_out = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int progress_round = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int slide_in_from_bottom = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int slide_in_from_top = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int slide_out_to_bottom = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int slide_out_to_top = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int zoomin = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int zoomout = 2130968586;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010026
			public const int civ_border_color = 2130772006;
			
			// aapt resource value: 0x7f010027
			public const int civ_border_overlay = 2130772007;
			
			// aapt resource value: 0x7f010025
			public const int civ_border_width = 2130772005;
			
			// aapt resource value: 0x7f010028
			public const int civ_fill_color = 2130772008;
			
			// aapt resource value: 0x7f010022
			public const int ptrAdapterViewBackground = 2130772002;
			
			// aapt resource value: 0x7f01000c
			public const int ptrAnimationStyle = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int ptrDrawable = 2130771974;
			
			// aapt resource value: 0x7f010024
			public const int ptrDrawableBottom = 2130772004;
			
			// aapt resource value: 0x7f010008
			public const int ptrDrawableEnd = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ptrDrawableStart = 2130771975;
			
			// aapt resource value: 0x7f010023
			public const int ptrDrawableTop = 2130772003;
			
			// aapt resource value: 0x7f010013
			public const int ptrFriction = 2130771987;
			
			// aapt resource value: 0x7f01000f
			public const int ptrGoogleProgressStyle = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int ptrGoogleViewStyle = 2130771982;
			
			// aapt resource value: 0x7f010001
			public const int ptrHeaderBackground = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int ptrHeaderSubTextColor = 2130771971;
			
			// aapt resource value: 0x7f01000a
			public const int ptrHeaderTextAppearance = 2130771978;
			
			// aapt resource value: 0x7f010002
			public const int ptrHeaderTextColor = 2130771970;
			
			// aapt resource value: 0x7f01001e
			public const int ptrHideRefeshableViewWhileRefreshingDuration = 2130771998;
			
			// aapt resource value: 0x7f01001b
			public const int ptrHideRefeshableViewWhileRefreshingEnabled = 2130771995;
			
			// aapt resource value: 0x7f01000d
			public const int ptrIndicatorStyle = 2130771981;
			
			// aapt resource value: 0x7f010017
			public const int ptrListViewExtrasEnabled = 2130771991;
			
			// aapt resource value: 0x7f010004
			public const int ptrMode = 2130771972;
			
			// aapt resource value: 0x7f010009
			public const int ptrOverScroll = 2130771977;
			
			// aapt resource value: 0x7f010010
			public const int ptrPullLabel = 2130771984;
			
			// aapt resource value: 0x7f010021
			public const int ptrRefeshableViewProgressBarOnCenterHeight = 2130772001;
			
			// aapt resource value: 0x7f010020
			public const int ptrRefeshableViewProgressBarOnCenterWidth = 2130772000;
			
			// aapt resource value: 0x7f010011
			public const int ptrRefreshLabel = 2130771985;
			
			// aapt resource value: 0x7f010000
			public const int ptrRefreshableViewBackground = 2130771968;
			
			// aapt resource value: 0x7f010012
			public const int ptrReleaseLabel = 2130771986;
			
			// aapt resource value: 0x7f010018
			public const int ptrRotateDrawableWhilePulling = 2130771992;
			
			// aapt resource value: 0x7f010016
			public const int ptrScrollingWhileRefreshingEnabled = 2130771990;
			
			// aapt resource value: 0x7f010019
			public const int ptrSetGoogleViewLayoutSizeToActionbarHeight = 2130771993;
			
			// aapt resource value: 0x7f01001d
			public const int ptrShowGoogleStyleViewAnimationDuration = 2130771997;
			
			// aapt resource value: 0x7f01001a
			public const int ptrShowGoogleStyleViewAnimationEnabled = 2130771994;
			
			// aapt resource value: 0x7f010005
			public const int ptrShowIndicator = 2130771973;
			
			// aapt resource value: 0x7f010014
			public const int ptrSmoothScrollDuration = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int ptrSmoothScrollLongDuration = 2130771989;
			
			// aapt resource value: 0x7f01000b
			public const int ptrSubHeaderTextAppearance = 2130771979;
			
			// aapt resource value: 0x7f01001f
			public const int ptrViewRefeshableViewProgressBarOnCenterWhileRefreshingDuration = 2130771999;
			
			// aapt resource value: 0x7f01001c
			public const int ptrViewRefeshableViewProgressBarOnCenterWhileRefreshingEnabled = 2130771996;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f0a000a
			public const int bg_gray = 2131361802;
			
			// aapt resource value: 0x7f0a0005
			public const int black = 2131361797;
			
			// aapt resource value: 0x7f0a0004
			public const int blue = 2131361796;
			
			// aapt resource value: 0x7f0a0001
			public const int color_nomal = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int color_pressed = 2131361794;
			
			// aapt resource value: 0x7f0a0006
			public const int darkblue = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int darkgray = 2131361799;
			
			// aapt resource value: 0x7f0a000c
			public const int halftransparent = 2131361804;
			
			// aapt resource value: 0x7f0a0008
			public const int ingray = 2131361800;
			
			// aapt resource value: 0x7f0a000b
			public const int light_orange = 2131361803;
			
			// aapt resource value: 0x7f0a0009
			public const int lightgray = 2131361801;
			
			// aapt resource value: 0x7f0a000e
			public const int pink = 2131361806;
			
			// aapt resource value: 0x7f0a0000
			public const int red = 2131361792;
			
			// aapt resource value: 0x7f0a000d
			public const int transparent = 2131361805;
			
			// aapt resource value: 0x7f0a0003
			public const int white = 2131361795;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070003
			public const int header_footer_left_right_padding = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int header_footer_top_bottom_padding = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int header_pull_to_refresh_image_padding = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int indicator_corner_radius = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int indicator_internal_padding = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int indicator_right_padding = 2131165184;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_right_blue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_right_gray = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int backselector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_blue_selector = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_orange_selector = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_red_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btnlogin = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button_unpress = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int callcustomphoneselector = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int checkboxselector = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int circle_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int circle_selected = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int dark_dot = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int default_ptr_flip = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int default_ptr_rotate = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int dot = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int guardian_actionmore_selector = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int guider1 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int guider2 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int guider3 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int guider4 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int head = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int home_tab_personal = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int home_tab_personal_selected = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_action_applyGuardian = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_action_back = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_action_bindingGuardian = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_action_content_discard = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_action_content_edit = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_action_content_save = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_action_more = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_action_rating_good = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_basicInformation = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_launch = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_launcher_lelaozu = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_launcher_lelaozu_bgWhite = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_login_eye_normal = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_login_eye_selected = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_login_password = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_login_rememberPassword_normal = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_login_rememberPassword_selected = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_login_username = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_medicalHistory = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_menu_alarm_normal = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_menu_alarm_selected = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_menu_guardian_normal = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_menu_guardian_selected = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic_menu_health_normal = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_menu_health_selected = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic_menu_mine_normal = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_menu_mine_selected = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_myInfomation_aboutUs = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_myInfomation_accountSecurity = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_myInfomation_advice = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic_myInfomation_cacheRemover = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ic_myInfomation_call = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ic_myInfomation_message = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ic_myInfomation_personalData = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ic_myInfomation_phone = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ic_myInfomation_userName = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic_myInfomation_versionDetection = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic_register_combox_normal = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic_register_combox_selected = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ic_register_eye_normal = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ic_register_eye_selected = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ic_register_message = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ic_register_password = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ic_register_phone = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int ic_register_username = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int ic_sex_man = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int ic_sex_woman = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int Icon = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int indicator_arrow = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int indicator_bg_bottom = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int indicator_bg_top = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int input_over = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int login_bg = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int login_edit = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int login_input = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int menu_bg = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int myInfomation_bgImage = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int myInfomation_headImage = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int myInfomation_next_arrow = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int myInfomation_setup_aboutus_logo = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int progress_1 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int progress_2 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int progress_3 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int progress_4 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int progress_5 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int progress_6 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int progress_7 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int progress_8 = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int progress_bg_holo_light = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int progress_horizontal_holo_light = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int progress_horizontal_holo_light_right = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int progress_indeterminate_horizontal_holo = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int progress_primary_holo_light = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int progress_secondary_holo_light = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int progressbar_indeterminate_holo1 = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int progressbar_indeterminate_holo2 = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int progressbar_indeterminate_holo3 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int progressbar_indeterminate_holo4 = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int progressbar_indeterminate_holo5 = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int progressbar_indeterminate_holo6 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int progressbar_indeterminate_holo7 = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int progressbar_indeterminate_holo8 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int radiobutton_selector = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int registerAgreeTextSelector = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int regitercheckboxselector = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int relativeLayoutSelector = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int setting = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int setting_btn = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int settingselector = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int shape = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int splash = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int tab_bg2 = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int textselector = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int tv_guardiandetailselector = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int tv_querryguardianselector = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int unbindselector = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int uparrow = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int user_center_camera = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int user_center_default = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int user_center_fav = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int user_center_integral = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int user_center_service = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int user_center_share = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int user_center_support = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int user_center_vip = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int whats_new_start_btn = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int white_dot = 2130837635;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08014f
			public const int action_edit = 2131231055;
			
			// aapt resource value: 0x7f080150
			public const int action_save = 2131231056;
			
			// aapt resource value: 0x7f080151
			public const int action_share = 2131231057;
			
			// aapt resource value: 0x7f08002b
			public const int alarmHandleDetailInfoListitemView = 2131230763;
			
			// aapt resource value: 0x7f0800ce
			public const int alarmViewPager = 2131230926;
			
			// aapt resource value: 0x7f08002f
			public const int alarmlistitemview = 2131230767;
			
			// aapt resource value: 0x7f080003
			public const int both = 2131230723;
			
			// aapt resource value: 0x7f080071
			public const int btn_Action = 2131230833;
			
			// aapt resource value: 0x7f0800d0
			public const int btn_BindGuardian = 2131230928;
			
			// aapt resource value: 0x7f080147
			public const int btn_Exit = 2131231047;
			
			// aapt resource value: 0x7f0800c7
			public const int btn_Login = 2131230919;
			
			// aapt resource value: 0x7f08013d
			public const int btn_Next = 2131231037;
			
			// aapt resource value: 0x7f080135
			public const int btn_RegistNext = 2131231029;
			
			// aapt resource value: 0x7f08004a
			public const int btn_Send = 2131230794;
			
			// aapt resource value: 0x7f08013b
			public const int btn_Submit = 2131231035;
			
			// aapt resource value: 0x7f080060
			public const int btn_action_agree = 2131230816;
			
			// aapt resource value: 0x7f080061
			public const int btn_action_disagree = 2131230817;
			
			// aapt resource value: 0x7f08004b
			public const int btn_cancel = 2131230795;
			
			// aapt resource value: 0x7f08004d
			public const int btn_confirm = 2131230797;
			
			// aapt resource value: 0x7f080046
			public const int btn_header_back = 2131230790;
			
			// aapt resource value: 0x7f08003d
			public const int btn_menu_bottom_alarm = 2131230781;
			
			// aapt resource value: 0x7f080040
			public const int btn_menu_bottom_guradian = 2131230784;
			
			// aapt resource value: 0x7f08003a
			public const int btn_menu_bottom_health = 2131230778;
			
			// aapt resource value: 0x7f080043
			public const int btn_menu_bottom_my = 2131230787;
			
			// aapt resource value: 0x7f0800ec
			public const int btn_my_search = 2131230956;
			
			// aapt resource value: 0x7f0800f7
			public const int btn_other_search = 2131230967;
			
			// aapt resource value: 0x7f080053
			public const int btn_pic_cancel = 2131230803;
			
			// aapt resource value: 0x7f080052
			public const int btn_pick_photo = 2131230802;
			
			// aapt resource value: 0x7f080075
			public const int btn_skip = 2131230837;
			
			// aapt resource value: 0x7f0800d1
			public const int btn_tab_myGuardian = 2131230929;
			
			// aapt resource value: 0x7f0800d4
			public const int btn_tab_myHealth = 2131230932;
			
			// aapt resource value: 0x7f0800d2
			public const int btn_tab_otherGuardian = 2131230930;
			
			// aapt resource value: 0x7f0800d5
			public const int btn_tab_otherHealth = 2131230933;
			
			// aapt resource value: 0x7f080051
			public const int btn_take_photo = 2131230801;
			
			// aapt resource value: 0x7f080136
			public const int cb_Agree = 2131231030;
			
			// aapt resource value: 0x7f0800c6
			public const int cb_Password = 2131230918;
			
			// aapt resource value: 0x7f080045
			public const int datepicker = 2131230789;
			
			// aapt resource value: 0x7f080004
			public const int disabled = 2131230724;
			
			// aapt resource value: 0x7f080077
			public const int dotImageLayout = 2131230839;
			
			// aapt resource value: 0x7f08014a
			public const int edit_ConfirmPwd = 2131231050;
			
			// aapt resource value: 0x7f0800fe
			public const int edit_IdCardNo = 2131230974;
			
			// aapt resource value: 0x7f0800c4
			public const int edit_PassWord = 2131230916;
			
			// aapt resource value: 0x7f080134
			public const int edit_Phone = 2131231028;
			
			// aapt resource value: 0x7f080148
			public const int edit_Pwd = 2131231048;
			
			// aapt resource value: 0x7f080132
			public const int edit_ReisterConfirmPwd = 2131231026;
			
			// aapt resource value: 0x7f08012f
			public const int edit_ReisterNickName = 2131231023;
			
			// aapt resource value: 0x7f080130
			public const int edit_ReisterPwd = 2131231024;
			
			// aapt resource value: 0x7f080139
			public const int edit_SecurityCode = 2131231033;
			
			// aapt resource value: 0x7f0800c2
			public const int edit_UserName = 2131230914;
			
			// aapt resource value: 0x7f080102
			public const int edit_birth = 2131230978;
			
			// aapt resource value: 0x7f080105
			public const int edit_email = 2131230981;
			
			// aapt resource value: 0x7f080104
			public const int edit_fixedPhone = 2131230980;
			
			// aapt resource value: 0x7f080106
			public const int edit_idCardLocation = 2131230982;
			
			// aapt resource value: 0x7f080108
			public const int edit_locationdeatil = 2131230984;
			
			// aapt resource value: 0x7f080107
			public const int edit_locationthreelevel = 2131230983;
			
			// aapt resource value: 0x7f0800e8
			public const int edit_my_endTime = 2131230952;
			
			// aapt resource value: 0x7f0800ef
			public const int edit_my_searchTime = 2131230959;
			
			// aapt resource value: 0x7f0800e7
			public const int edit_my_startTime = 2131230951;
			
			// aapt resource value: 0x7f08014d
			public const int edit_newpassword = 2131231053;
			
			// aapt resource value: 0x7f08014e
			public const int edit_newpasswordconfirm = 2131231054;
			
			// aapt resource value: 0x7f08014c
			public const int edit_oldpassword = 2131231052;
			
			// aapt resource value: 0x7f0800f2
			public const int edit_other_endTime = 2131230962;
			
			// aapt resource value: 0x7f0800fa
			public const int edit_other_searchTime = 2131230970;
			
			// aapt resource value: 0x7f0800f1
			public const int edit_other_startTime = 2131230961;
			
			// aapt resource value: 0x7f080103
			public const int edit_phoneNumberOne = 2131230979;
			
			// aapt resource value: 0x7f0800fd
			public const int edit_trueName = 2131230973;
			
			// aapt resource value: 0x7f080127
			public const int fl_inner = 2131231015;
			
			// aapt resource value: 0x7f080124
			public const int fl_inner_for_google_style = 2131231012;
			
			// aapt resource value: 0x7f080058
			public const int getApplyInfoListItemView = 2131230808;
			
			// aapt resource value: 0x7f080005
			public const int google = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int gridview = 2131230720;
			
			// aapt resource value: 0x7f0800d3
			public const int guardianViewpager = 2131230931;
			
			// aapt resource value: 0x7f080059
			public const int guardian_img_head = 2131230809;
			
			// aapt resource value: 0x7f08006e
			public const int guardianlistitemview = 2131230830;
			
			// aapt resource value: 0x7f080076
			public const int guiderviewpager = 2131230838;
			
			// aapt resource value: 0x7f0800d6
			public const int healthViewpager = 2131230934;
			
			// aapt resource value: 0x7f080078
			public const int health_Scroll = 2131230840;
			
			// aapt resource value: 0x7f0800c0
			public const int healthitemview = 2131230912;
			
			// aapt resource value: 0x7f0800ca
			public const int id_mainContent = 2131230922;
			
			// aapt resource value: 0x7f08003c
			public const int id_tab_bottom_alarm = 2131230780;
			
			// aapt resource value: 0x7f08003f
			public const int id_tab_bottom_guardian = 2131230783;
			
			// aapt resource value: 0x7f080039
			public const int id_tab_bottom_health = 2131230777;
			
			// aapt resource value: 0x7f080042
			public const int id_tab_bottom_my = 2131230786;
			
			// aapt resource value: 0x7f080055
			public const int id_tv_loadingmsg = 2131230805;
			
			// aapt resource value: 0x7f08007d
			public const int img_BMI_Arraw = 2131230845;
			
			// aapt resource value: 0x7f080082
			public const int img_BloodGlucose_Arraw = 2131230850;
			
			// aapt resource value: 0x7f0800a2
			public const int img_BloodLipidParaFour_Arraw = 2131230882;
			
			// aapt resource value: 0x7f08009e
			public const int img_BloodLipidParaOne_Arraw = 2131230878;
			
			// aapt resource value: 0x7f0800aa
			public const int img_BloodLipidParaThree_Arraw = 2131230890;
			
			// aapt resource value: 0x7f0800a6
			public const int img_BloodLipidParaTwo_Arraw = 2131230886;
			
			// aapt resource value: 0x7f080087
			public const int img_BloodOxygenParaOne_Arraw = 2131230855;
			
			// aapt resource value: 0x7f080096
			public const int img_BodyTemperature_Arraw = 2131230870;
			
			// aapt resource value: 0x7f080091
			public const int img_BreathCapacity_Arraw = 2131230865;
			
			// aapt resource value: 0x7f08008c
			public const int img_HeartRate_Arraw = 2131230860;
			
			// aapt resource value: 0x7f08011e
			public const int img_IdCardLocation_arraw = 2131231006;
			
			// aapt resource value: 0x7f08010e
			public const int img_IdCardNo_arraw = 2131230990;
			
			// aapt resource value: 0x7f080121
			public const int img_TrueLocation_arraw = 2131231009;
			
			// aapt resource value: 0x7f0800af
			public const int img_UrineRoutinePH_Arraw = 2131230895;
			
			// aapt resource value: 0x7f0800b3
			public const int img_UrineRoutineSG_Arraw = 2131230899;
			
			// aapt resource value: 0x7f0800b7
			public const int img_UrineRoutineURO_Arraw = 2131230903;
			
			// aapt resource value: 0x7f080140
			public const int img_aboutUs = 2131231040;
			
			// aapt resource value: 0x7f0800e1
			public const int img_accountSecurity_arraw = 2131230945;
			
			// aapt resource value: 0x7f0800e4
			public const int img_advice_arraw = 2131230948;
			
			// aapt resource value: 0x7f0800de
			public const int img_basic_arraw = 2131230942;
			
			// aapt resource value: 0x7f080113
			public const int img_birth_arraw = 2131230995;
			
			// aapt resource value: 0x7f080145
			public const int img_cacheRemover = 2131231045;
			
			// aapt resource value: 0x7f080146
			public const int img_cacheRemover_arraw = 2131231046;
			
			// aapt resource value: 0x7f0800e6
			public const int img_callCustom = 2131230950;
			
			// aapt resource value: 0x7f08011b
			public const int img_email_arraw = 2131231003;
			
			// aapt resource value: 0x7f0800c5
			public const int img_eye = 2131230917;
			
			// aapt resource value: 0x7f08014b
			public const int img_eye_ConfirmPwd = 2131231051;
			
			// aapt resource value: 0x7f080149
			public const int img_eye_Pwd = 2131231049;
			
			// aapt resource value: 0x7f080133
			public const int img_eye_ReisterConfirmPwd = 2131231027;
			
			// aapt resource value: 0x7f080131
			public const int img_eye_ReisterPwd = 2131231025;
			
			// aapt resource value: 0x7f080118
			public const int img_fixedPhone_arraw = 2131231000;
			
			// aapt resource value: 0x7f080111
			public const int img_gender_arraw = 2131230993;
			
			// aapt resource value: 0x7f0800d8
			public const int img_head = 2131230936;
			
			// aapt resource value: 0x7f08001b
			public const int img_identity_arraw = 2131230747;
			
			// aapt resource value: 0x7f08000f
			public const int img_loginPwd_arraw = 2131230735;
			
			// aapt resource value: 0x7f080013
			public const int img_payPwd_arraw = 2131230739;
			
			// aapt resource value: 0x7f0800e0
			public const int img_person_accountSecurity = 2131230944;
			
			// aapt resource value: 0x7f0800e3
			public const int img_person_advice = 2131230947;
			
			// aapt resource value: 0x7f0800dd
			public const int img_person_basic = 2131230941;
			
			// aapt resource value: 0x7f080017
			public const int img_phoneBind_arraw = 2131230743;
			
			// aapt resource value: 0x7f080116
			public const int img_phoneNumber_arraw = 2131230998;
			
			// aapt resource value: 0x7f0800d9
			public const int img_setting = 2131230937;
			
			// aapt resource value: 0x7f08005d
			public const int img_sex = 2131230813;
			
			// aapt resource value: 0x7f08010c
			public const int img_trueName_arraw = 2131230988;
			
			// aapt resource value: 0x7f080142
			public const int img_versionCheck = 2131231042;
			
			// aapt resource value: 0x7f080143
			public const int img_versionCheck_arraw = 2131231043;
			
			// aapt resource value: 0x7f0800cd
			public const int iv_bottom_line = 2131230925;
			
			// aapt resource value: 0x7f080074
			public const int iv_start_use = 2131230836;
			
			// aapt resource value: 0x7f08005a
			public const int linearText = 2131230810;
			
			// aapt resource value: 0x7f080073
			public const int ll_ApplyGuardian = 2131230835;
			
			// aapt resource value: 0x7f080034
			public const int ll_MainGuardian = 2131230772;
			
			// aapt resource value: 0x7f08005f
			public const int ll_action = 2131230815;
			
			// aapt resource value: 0x7f0800cf
			public const int ll_actionBar = 2131230927;
			
			// aapt resource value: 0x7f080072
			public const int ll_bindGuardian = 2131230834;
			
			// aapt resource value: 0x7f0800d7
			public const int ll_person = 2131230935;
			
			// aapt resource value: 0x7f08012e
			public const int ll_register = 2131231022;
			
			// aapt resource value: 0x7f080054
			public const int loadingImageView = 2131230804;
			
			// aapt resource value: 0x7f0800ed
			public const int lv_MyAlarm = 2131230957;
			
			// aapt resource value: 0x7f0800f0
			public const int lv_MyHealth = 2131230960;
			
			// aapt resource value: 0x7f0800f9
			public const int lv_OtherGuardian = 2131230969;
			
			// aapt resource value: 0x7f080062
			public const int lv_guardianApply = 2131230818;
			
			// aapt resource value: 0x7f08002a
			public const int lv_handleDetail = 2131230762;
			
			// aapt resource value: 0x7f0800ee
			public const int lv_myGuardian = 2131230958;
			
			// aapt resource value: 0x7f0800f8
			public const int lv_otherAlarm = 2131230968;
			
			// aapt resource value: 0x7f0800fb
			public const int lv_otherHealth = 2131230971;
			
			// aapt resource value: 0x7f080037
			public const int lv_searchGuardian = 2131230775;
			
			// aapt resource value: 0x7f080038
			public const int ly_main_tab_bottom = 2131230776;
			
			// aapt resource value: 0x7f080006
			public const int manualOnly = 2131230726;
			
			// aapt resource value: 0x7f080050
			public const int msgContent = 2131230800;
			
			// aapt resource value: 0x7f08004e
			public const int msgIcon = 2131230798;
			
			// aapt resource value: 0x7f08004f
			public const int msgTitle = 2131230799;
			
			// aapt resource value: 0x7f080123
			public const int progressbar = 2131231011;
			
			// aapt resource value: 0x7f080007
			public const int pullDownFromTop = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int pullFromEnd = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int pullFromStart = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int pullUpFromBottom = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int pull_refresh_scrollview = 2131230732;
			
			// aapt resource value: 0x7f080128
			public const int pull_to_refresh_image = 2131231016;
			
			// aapt resource value: 0x7f080129
			public const int pull_to_refresh_progress = 2131231017;
			
			// aapt resource value: 0x7f080126
			public const int pull_to_refresh_sub_text = 2131231014;
			
			// aapt resource value: 0x7f080125
			public const int pull_to_refresh_text = 2131231013;
			
			// aapt resource value: 0x7f08012c
			public const int pulling_left_progressbar = 2131231020;
			
			// aapt resource value: 0x7f08012a
			public const int pulling_progress = 2131231018;
			
			// aapt resource value: 0x7f08012d
			public const int pulling_right_progressbar = 2131231021;
			
			// aapt resource value: 0x7f0800ff
			public const int radioGroup = 2131230975;
			
			// aapt resource value: 0x7f080101
			public const int rbtn_female = 2131230977;
			
			// aapt resource value: 0x7f080100
			public const int rbtn_male = 2131230976;
			
			// aapt resource value: 0x7f0800f4
			public const int rbtn_other_paul = 2131230964;
			
			// aapt resource value: 0x7f0800f5
			public const int rbtn_other_trip = 2131230965;
			
			// aapt resource value: 0x7f0800ea
			public const int rbtn_paul = 2131230954;
			
			// aapt resource value: 0x7f0800eb
			public const int rbtn_trip = 2131230955;
			
			// aapt resource value: 0x7f08012b
			public const int refreshing_progress = 2131231019;
			
			// aapt resource value: 0x7f0800e9
			public const int rgp_alarmWay = 2131230953;
			
			// aapt resource value: 0x7f0800f3
			public const int rgp_other_alarmWay = 2131230963;
			
			// aapt resource value: 0x7f0800c3
			public const int rl_PassWord = 2131230915;
			
			// aapt resource value: 0x7f0800c1
			public const int rl_UserName = 2131230913;
			
			// aapt resource value: 0x7f08013f
			public const int rl_aboutUs = 2131231039;
			
			// aapt resource value: 0x7f080144
			public const int rl_cacheRemover = 2131231044;
			
			// aapt resource value: 0x7f080112
			public const int rl_person_Birth = 2131230994;
			
			// aapt resource value: 0x7f080110
			public const int rl_person_Gender = 2131230992;
			
			// aapt resource value: 0x7f08011d
			public const int rl_person_IdCardLocation = 2131231005;
			
			// aapt resource value: 0x7f08010d
			public const int rl_person_IdCardNo = 2131230989;
			
			// aapt resource value: 0x7f08010b
			public const int rl_person_TrueName = 2131230987;
			
			// aapt resource value: 0x7f080109
			public const int rl_person_UserName = 2131230985;
			
			// aapt resource value: 0x7f0800df
			public const int rl_person_accountSecurity = 2131230943;
			
			// aapt resource value: 0x7f0800e2
			public const int rl_person_advice = 2131230946;
			
			// aapt resource value: 0x7f0800dc
			public const int rl_person_basic = 2131230940;
			
			// aapt resource value: 0x7f08011a
			public const int rl_person_email = 2131231002;
			
			// aapt resource value: 0x7f080117
			public const int rl_person_fixedPhone = 2131230999;
			
			// aapt resource value: 0x7f080019
			public const int rl_person_identity = 2131230745;
			
			// aapt resource value: 0x7f08000d
			public const int rl_person_loginPwd = 2131230733;
			
			// aapt resource value: 0x7f080011
			public const int rl_person_payPwd = 2131230737;
			
			// aapt resource value: 0x7f080015
			public const int rl_person_phoneBind = 2131230741;
			
			// aapt resource value: 0x7f080115
			public const int rl_person_phoneNumber = 2131230997;
			
			// aapt resource value: 0x7f080120
			public const int rl_person_trueLocation = 2131231008;
			
			// aapt resource value: 0x7f080141
			public const int rl_versionCheck = 2131231041;
			
			// aapt resource value: 0x7f08001d
			public const int scrollView1 = 2131230749;
			
			// aapt resource value: 0x7f080002
			public const int scrollview = 2131230722;
			
			// aapt resource value: 0x7f08013c
			public const int searchGuardianListItemView = 2131231036;
			
			// aapt resource value: 0x7f080035
			public const int searchView = 2131230773;
			
			// aapt resource value: 0x7f0800f6
			public const int sp_other_guardian = 2131230966;
			
			// aapt resource value: 0x7f08007b
			public const int tv_BMI = 2131230843;
			
			// aapt resource value: 0x7f08007c
			public const int tv_BMI_High = 2131230844;
			
			// aapt resource value: 0x7f08007e
			public const int tv_BMI_Low = 2131230846;
			
			// aapt resource value: 0x7f08007a
			public const int tv_BMI_Show = 2131230842;
			
			// aapt resource value: 0x7f080114
			public const int tv_Birth = 2131230996;
			
			// aapt resource value: 0x7f080080
			public const int tv_BloodGlucose = 2131230848;
			
			// aapt resource value: 0x7f080081
			public const int tv_BloodGlucose_High = 2131230849;
			
			// aapt resource value: 0x7f080083
			public const int tv_BloodGlucose_Low = 2131230851;
			
			// aapt resource value: 0x7f08007f
			public const int tv_BloodGlucose_Show = 2131230847;
			
			// aapt resource value: 0x7f0800a0
			public const int tv_BloodLipidParaFour = 2131230880;
			
			// aapt resource value: 0x7f0800a1
			public const int tv_BloodLipidParaFour_High = 2131230881;
			
			// aapt resource value: 0x7f0800a3
			public const int tv_BloodLipidParaFour_Low = 2131230883;
			
			// aapt resource value: 0x7f08009c
			public const int tv_BloodLipidParaOne = 2131230876;
			
			// aapt resource value: 0x7f08009d
			public const int tv_BloodLipidParaOne_High = 2131230877;
			
			// aapt resource value: 0x7f08009f
			public const int tv_BloodLipidParaOne_Low = 2131230879;
			
			// aapt resource value: 0x7f0800a8
			public const int tv_BloodLipidParaThree = 2131230888;
			
			// aapt resource value: 0x7f0800a9
			public const int tv_BloodLipidParaThree_High = 2131230889;
			
			// aapt resource value: 0x7f0800ab
			public const int tv_BloodLipidParaThree_Low = 2131230891;
			
			// aapt resource value: 0x7f0800a4
			public const int tv_BloodLipidParaTwo = 2131230884;
			
			// aapt resource value: 0x7f0800a5
			public const int tv_BloodLipidParaTwo_High = 2131230885;
			
			// aapt resource value: 0x7f0800a7
			public const int tv_BloodLipidParaTwo_Low = 2131230887;
			
			// aapt resource value: 0x7f08009b
			public const int tv_BloodLipid_Show = 2131230875;
			
			// aapt resource value: 0x7f080085
			public const int tv_BloodOxygenParaOne = 2131230853;
			
			// aapt resource value: 0x7f080086
			public const int tv_BloodOxygenParaOne_High = 2131230854;
			
			// aapt resource value: 0x7f080088
			public const int tv_BloodOxygenParaOne_Low = 2131230856;
			
			// aapt resource value: 0x7f080084
			public const int tv_BloodOxygen_Show = 2131230852;
			
			// aapt resource value: 0x7f08009a
			public const int tv_BloodPressureParaOne = 2131230874;
			
			// aapt resource value: 0x7f080099
			public const int tv_BloodPressureParaTwo = 2131230873;
			
			// aapt resource value: 0x7f080098
			public const int tv_BloodPressure_Show = 2131230872;
			
			// aapt resource value: 0x7f080094
			public const int tv_BodyTemperature = 2131230868;
			
			// aapt resource value: 0x7f080095
			public const int tv_BodyTemperature_High = 2131230869;
			
			// aapt resource value: 0x7f080097
			public const int tv_BodyTemperature_Low = 2131230871;
			
			// aapt resource value: 0x7f080093
			public const int tv_BodyTemperature_Show = 2131230867;
			
			// aapt resource value: 0x7f08008f
			public const int tv_BreathCapacity = 2131230863;
			
			// aapt resource value: 0x7f080090
			public const int tv_BreathCapacity_High = 2131230864;
			
			// aapt resource value: 0x7f080092
			public const int tv_BreathCapacity_Low = 2131230866;
			
			// aapt resource value: 0x7f08008e
			public const int tv_BreathCapacity_Show = 2131230862;
			
			// aapt resource value: 0x7f080065
			public const int tv_Brnl = 2131230821;
			
			// aapt resource value: 0x7f080068
			public const int tv_ContactAddress = 2131230824;
			
			// aapt resource value: 0x7f08006a
			public const int tv_Email = 2131230826;
			
			// aapt resource value: 0x7f080064
			public const int tv_Gender = 2131230820;
			
			// aapt resource value: 0x7f08005c
			public const int tv_GuardianStatus = 2131230812;
			
			// aapt resource value: 0x7f08008a
			public const int tv_HeartRate = 2131230858;
			
			// aapt resource value: 0x7f08008b
			public const int tv_HeartRate_High = 2131230859;
			
			// aapt resource value: 0x7f08008d
			public const int tv_HeartRate_Low = 2131230861;
			
			// aapt resource value: 0x7f080089
			public const int tv_HeartRate_Show = 2131230857;
			
			// aapt resource value: 0x7f08006b
			public const int tv_Height = 2131230827;
			
			// aapt resource value: 0x7f08006d
			public const int tv_HereditaryDisease = 2131230829;
			
			// aapt resource value: 0x7f080067
			public const int tv_IDNumber = 2131230823;
			
			// aapt resource value: 0x7f08011f
			public const int tv_IdCardLocation = 2131231007;
			
			// aapt resource value: 0x7f08010f
			public const int tv_IdCardNo = 2131230991;
			
			// aapt resource value: 0x7f08005b
			public const int tv_Name = 2131230811;
			
			// aapt resource value: 0x7f080066
			public const int tv_PhoneNumberOne = 2131230822;
			
			// aapt resource value: 0x7f080138
			public const int tv_PhoneShow = 2131231032;
			
			// aapt resource value: 0x7f0800c9
			public const int tv_Register = 2131230921;
			
			// aapt resource value: 0x7f08013a
			public const int tv_SendCodeStatusShow = 2131231034;
			
			// aapt resource value: 0x7f080069
			public const int tv_TelePhoneNumber = 2131230825;
			
			// aapt resource value: 0x7f080079
			public const int tv_TestTime = 2131230841;
			
			// aapt resource value: 0x7f080122
			public const int tv_TrueLocation = 2131231010;
			
			// aapt resource value: 0x7f080063
			public const int tv_TrueName = 2131230819;
			
			// aapt resource value: 0x7f0800bd
			public const int tv_UrineRoutineBIL = 2131230909;
			
			// aapt resource value: 0x7f0800ba
			public const int tv_UrineRoutineBLO = 2131230906;
			
			// aapt resource value: 0x7f0800bc
			public const int tv_UrineRoutineGLU = 2131230908;
			
			// aapt resource value: 0x7f0800bb
			public const int tv_UrineRoutineKET = 2131230907;
			
			// aapt resource value: 0x7f0800ad
			public const int tv_UrineRoutinePH = 2131230893;
			
			// aapt resource value: 0x7f0800ae
			public const int tv_UrineRoutinePH_High = 2131230894;
			
			// aapt resource value: 0x7f0800b0
			public const int tv_UrineRoutinePH_Low = 2131230896;
			
			// aapt resource value: 0x7f0800bf
			public const int tv_UrineRoutineRBC = 2131230911;
			
			// aapt resource value: 0x7f0800be
			public const int tv_UrineRoutineRPO = 2131230910;
			
			// aapt resource value: 0x7f0800b1
			public const int tv_UrineRoutineSG = 2131230897;
			
			// aapt resource value: 0x7f0800b2
			public const int tv_UrineRoutineSG_High = 2131230898;
			
			// aapt resource value: 0x7f0800b4
			public const int tv_UrineRoutineSG_Low = 2131230900;
			
			// aapt resource value: 0x7f0800b5
			public const int tv_UrineRoutineURO = 2131230901;
			
			// aapt resource value: 0x7f0800b6
			public const int tv_UrineRoutineURO_High = 2131230902;
			
			// aapt resource value: 0x7f0800b8
			public const int tv_UrineRoutineURO_Low = 2131230904;
			
			// aapt resource value: 0x7f0800b9
			public const int tv_UrineRoutineWBC = 2131230905;
			
			// aapt resource value: 0x7f0800ac
			public const int tv_UrineRoutine_Show = 2131230892;
			
			// aapt resource value: 0x7f08010a
			public const int tv_UserName = 2131230986;
			
			// aapt resource value: 0x7f08006c
			public const int tv_Weight = 2131230828;
			
			// aapt resource value: 0x7f080033
			public const int tv_alarmContent = 2131230771;
			
			// aapt resource value: 0x7f080032
			public const int tv_alarmStatus = 2131230770;
			
			// aapt resource value: 0x7f080031
			public const int tv_alarmTime = 2131230769;
			
			// aapt resource value: 0x7f080030
			public const int tv_alarmTrueName = 2131230768;
			
			// aapt resource value: 0x7f08005e
			public const int tv_applyContent = 2131230814;
			
			// aapt resource value: 0x7f08000b
			public const int tv_appversion = 2131230731;
			
			// aapt resource value: 0x7f0800e5
			public const int tv_customPhone = 2131230949;
			
			// aapt resource value: 0x7f080070
			public const int tv_detail = 2131230832;
			
			// aapt resource value: 0x7f08001e
			public const int tv_detail_alamTime = 2131230750;
			
			// aapt resource value: 0x7f080021
			public const int tv_detail_alarmContent = 2131230753;
			
			// aapt resource value: 0x7f080023
			public const int tv_detail_alarmDeviceId = 2131230755;
			
			// aapt resource value: 0x7f08001f
			public const int tv_detail_alarmPosition = 2131230751;
			
			// aapt resource value: 0x7f080026
			public const int tv_detail_alarmWay = 2131230758;
			
			// aapt resource value: 0x7f080028
			public const int tv_detail_cTrueName = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int tv_detail_cphoneNumberOne = 2131230761;
			
			// aapt resource value: 0x7f080022
			public const int tv_detail_deviceElectricity = 2131230754;
			
			// aapt resource value: 0x7f080027
			public const int tv_detail_handleUserType = 2131230759;
			
			// aapt resource value: 0x7f080024
			public const int tv_detail_remark = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int tv_detail_status = 2131230757;
			
			// aapt resource value: 0x7f080020
			public const int tv_detail_trueName = 2131230752;
			
			// aapt resource value: 0x7f08011c
			public const int tv_email = 2131231004;
			
			// aapt resource value: 0x7f080119
			public const int tv_fixedPhone = 2131231001;
			
			// aapt resource value: 0x7f0800c8
			public const int tv_forgetPwd = 2131230920;
			
			// aapt resource value: 0x7f08002d
			public const int tv_handledetail_handleContent = 2131230765;
			
			// aapt resource value: 0x7f08002c
			public const int tv_handledetail_handleTime = 2131230764;
			
			// aapt resource value: 0x7f08002e
			public const int tv_handledetail_remark = 2131230766;
			
			// aapt resource value: 0x7f080048
			public const int tv_header_save = 2131230792;
			
			// aapt resource value: 0x7f080047
			public const int tv_header_title = 2131230791;
			
			// aapt resource value: 0x7f08001c
			public const int tv_identity = 2131230748;
			
			// aapt resource value: 0x7f080137
			public const int tv_linkServiceAgree = 2131231031;
			
			// aapt resource value: 0x7f08006f
			public const int tv_location = 2131230831;
			
			// aapt resource value: 0x7f080010
			public const int tv_loginPwd = 2131230736;
			
			// aapt resource value: 0x7f08003e
			public const int tv_menu_bottom_alarm = 2131230782;
			
			// aapt resource value: 0x7f080041
			public const int tv_menu_bottom_guardian = 2131230785;
			
			// aapt resource value: 0x7f08003b
			public const int tv_menu_bottom_health = 2131230779;
			
			// aapt resource value: 0x7f080044
			public const int tv_menu_bottom_my = 2131230788;
			
			// aapt resource value: 0x7f080057
			public const int tv_msgContent = 2131230807;
			
			// aapt resource value: 0x7f0800da
			public const int tv_nickName = 2131230938;
			
			// aapt resource value: 0x7f080014
			public const int tv_payPwd = 2131230740;
			
			// aapt resource value: 0x7f08001a
			public const int tv_person_identity = 2131230746;
			
			// aapt resource value: 0x7f08000e
			public const int tv_person_loginPwd = 2131230734;
			
			// aapt resource value: 0x7f080012
			public const int tv_person_payPwd = 2131230738;
			
			// aapt resource value: 0x7f080016
			public const int tv_person_phoneBind = 2131230742;
			
			// aapt resource value: 0x7f080018
			public const int tv_phoneBind = 2131230744;
			
			// aapt resource value: 0x7f08004c
			public const int tv_phoneNumber = 2131230796;
			
			// aapt resource value: 0x7f0800db
			public const int tv_phonenumber = 2131230939;
			
			// aapt resource value: 0x7f08013e
			public const int tv_service_agree = 2131231038;
			
			// aapt resource value: 0x7f0800cb
			public const int tv_tab_myAlarm = 2131230923;
			
			// aapt resource value: 0x7f0800cc
			public const int tv_tab_otherAlarm = 2131230924;
			
			// aapt resource value: 0x7f080056
			public const int tv_title = 2131230806;
			
			// aapt resource value: 0x7f0800fc
			public const int tv_userName = 2131230972;
			
			// aapt resource value: 0x7f080049
			public const int txt_ApplyMsgContent = 2131230793;
			
			// aapt resource value: 0x7f080036
			public const int txt_Querry = 2131230774;
			
			// aapt resource value: 0x7f080001
			public const int webview = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutUsLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AccountSecurityLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AdviceLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int AlarmDetailInfoLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int alarmHandleDetailInfoListitemView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int alarmListitemView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int BindGuardianLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int bottom_bar = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int commondatepickerlayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int custom_title_bar = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int custom_titlebar_action = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int customapplybinddialog = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int customconfirmphonedialog = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int customer_notitfication_layout = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int customheadselectordialog = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int customprogressdialog = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int customunbinddialogLayout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int getApplyInfoListItemView = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int GuardianApplyLayout = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int GuardianDetailInfoLayout = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int guardianListitemView = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int GuardianPopupWindowLayout = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Guider_Four = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Guider_One = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int Guider_Three = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Guider_Two = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int GuiderLayout = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int HealthDetailInfoLayout = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int healthListItemView = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int LoginLayout = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int Main = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int Main_Tab_AlarmLayout = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int Main_Tab_GuardianLayout = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int Main_Tab_HealthLayout = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int Main_Tab_MyLayout = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int MyAlarmFragLayout = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int MyGuardianFragLayout = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int MyHealthFragLayout = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int OtherAlarmFragLayout = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int OtherGuardianFragLayout = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int OtherHealthFragLayout = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int PersonBasicLayout = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int PersonInfoBirthLayout = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int PersonInfoEmailLayout = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int PersonInfoFixedPhoneLayout = 2130903084;
			
			// aapt resource value: 0x7f03002d
			public const int PersonInfoGenderLayout = 2130903085;
			
			// aapt resource value: 0x7f03002e
			public const int PersonInfoIdCardNoLayout = 2130903086;
			
			// aapt resource value: 0x7f03002f
			public const int PersonInfoIdCardNoLocationLayout = 2130903087;
			
			// aapt resource value: 0x7f030030
			public const int PersonInfoLayout = 2130903088;
			
			// aapt resource value: 0x7f030031
			public const int PersonInfoTrueLocationLayout = 2130903089;
			
			// aapt resource value: 0x7f030032
			public const int PersonInfoTrueNameLayout = 2130903090;
			
			// aapt resource value: 0x7f030033
			public const int progressbar = 2130903091;
			
			// aapt resource value: 0x7f030034
			public const int pull_to_refresh_header_google_style = 2130903092;
			
			// aapt resource value: 0x7f030035
			public const int pull_to_refresh_header_horizontal = 2130903093;
			
			// aapt resource value: 0x7f030036
			public const int pull_to_refresh_header_vertical = 2130903094;
			
			// aapt resource value: 0x7f030037
			public const int pull_to_refresh_progress_google_style = 2130903095;
			
			// aapt resource value: 0x7f030038
			public const int pulling_progress_layout = 2130903096;
			
			// aapt resource value: 0x7f030039
			public const int RegisterLayout = 2130903097;
			
			// aapt resource value: 0x7f03003a
			public const int RegisterResultLayout = 2130903098;
			
			// aapt resource value: 0x7f03003b
			public const int searchguardianListItemView = 2130903099;
			
			// aapt resource value: 0x7f03003c
			public const int SendSecurityCodeLayout = 2130903100;
			
			// aapt resource value: 0x7f03003d
			public const int ServiceAgreeLayout = 2130903101;
			
			// aapt resource value: 0x7f03003e
			public const int SetLayout = 2130903102;
			
			// aapt resource value: 0x7f03003f
			public const int SetPasswordLayout = 2130903103;
			
			// aapt resource value: 0x7f030040
			public const int SplashLayout = 2130903104;
			
			// aapt resource value: 0x7f030041
			public const int UpdatePasswordLayout = 2130903105;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0c0000
			public const int main_menu = 2131492864;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int pull_event = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int refreshing_sound = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int reset_sound = 2131099650;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090016
			public const int Register = 2131296278;
			
			// aapt resource value: 0x7f090006
			public const int app_name = 2131296262;
			
			// aapt resource value: 0x7f09000b
			public const int confirm = 2131296267;
			
			// aapt resource value: 0x7f090018
			public const int customphoneNumber = 2131296280;
			
			// aapt resource value: 0x7f09000c
			public const int edit = 2131296268;
			
			// aapt resource value: 0x7f090009
			public const int forgetPwd = 2131296265;
			
			// aapt resource value: 0x7f09000e
			public const int loadMsg = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int loginMsg = 2131296271;
			
			// aapt resource value: 0x7f090008
			public const int newAcount = 2131296264;
			
			// aapt resource value: 0x7f090010
			public const int pullDownLbl = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int pullDownRefreshLbl = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int pullDownReleaseLbl = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int pullUpLbl = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int pullUpRefreshLbl = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int pullUpReleaseLbl = 2131296277;
			
			// aapt resource value: 0x7f090003
			public const int pull_to_refresh_from_bottom_pull_label = 2131296259;
			
			// aapt resource value: 0x7f090005
			public const int pull_to_refresh_from_bottom_refreshing_label = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int pull_to_refresh_from_bottom_release_label = 2131296260;
			
			// aapt resource value: 0x7f090000
			public const int pull_to_refresh_pull_label = 2131296256;
			
			// aapt resource value: 0x7f090002
			public const int pull_to_refresh_refreshing_label = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int pull_to_refresh_release_label = 2131296257;
			
			// aapt resource value: 0x7f09000a
			public const int save = 2131296266;
			
			// aapt resource value: 0x7f090017
			public const int securityCode = 2131296279;
			
			// aapt resource value: 0x7f090007
			public const int serviceAgree = 2131296263;
			
			// aapt resource value: 0x7f09000d
			public const int share = 2131296269;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0b0000
			public const int AnimationPreview = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int Animationbottom = 2131427329;
			
			// aapt resource value: 0x7f0b0006
			public const int AppTheme = 2131427334;
			
			// aapt resource value: 0x7f0b0002
			public const int CustomDialog = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int CustomProgressDialog = 2131427331;
			
			// aapt resource value: 0x7f0b0005
			public const int MyCustomTheme = 2131427333;
			
			// aapt resource value: 0x7f0b0004
			public const int TitleBarBackground = 2131427332;
			
			// aapt resource value: 0x7f0b0007
			public const int action_bar = 2131427335;
			
			// aapt resource value: 0x7f0b0009
			public const int action_bar_tv = 2131427337;
			
			// aapt resource value: 0x7f0b0008
			public const int bottom_menu_tv = 2131427336;
			
			// aapt resource value: 0x7f0b000f
			public const int btn_head_pop = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public const int personbasic_ll_layout = 2131427344;
			
			// aapt resource value: 0x7f0b0011
			public const int personbasic_tv_key = 2131427345;
			
			// aapt resource value: 0x7f0b0012
			public const int personbasic_value = 2131427346;
			
			// aapt resource value: 0x7f0b000c
			public const int pulltorefresh_lv = 2131427340;
			
			// aapt resource value: 0x7f0b000b
			public const int tab_btn_style = 2131427339;
			
			// aapt resource value: 0x7f0b000a
			public const int tab_linerlayout = 2131427338;
			
			// aapt resource value: 0x7f0b000d
			public const int tv_key = 2131427341;
			
			// aapt resource value: 0x7f0b000e
			public const int tv_value = 2131427342;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int pulltorefresh = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleImageView = new int[] {
					2130772005,
					2130772006,
					2130772007,
					2130772008};
			
			// aapt resource value: 1
			public const int CircleImageView_civ_border_color = 1;
			
			// aapt resource value: 2
			public const int CircleImageView_civ_border_overlay = 2;
			
			// aapt resource value: 0
			public const int CircleImageView_civ_border_width = 0;
			
			// aapt resource value: 3
			public const int CircleImageView_civ_fill_color = 3;
			
			public static int[] PullToRefresh = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004};
			
			// aapt resource value: 34
			public const int PullToRefresh_ptrAdapterViewBackground = 34;
			
			// aapt resource value: 12
			public const int PullToRefresh_ptrAnimationStyle = 12;
			
			// aapt resource value: 6
			public const int PullToRefresh_ptrDrawable = 6;
			
			// aapt resource value: 36
			public const int PullToRefresh_ptrDrawableBottom = 36;
			
			// aapt resource value: 8
			public const int PullToRefresh_ptrDrawableEnd = 8;
			
			// aapt resource value: 7
			public const int PullToRefresh_ptrDrawableStart = 7;
			
			// aapt resource value: 35
			public const int PullToRefresh_ptrDrawableTop = 35;
			
			// aapt resource value: 19
			public const int PullToRefresh_ptrFriction = 19;
			
			// aapt resource value: 15
			public const int PullToRefresh_ptrGoogleProgressStyle = 15;
			
			// aapt resource value: 14
			public const int PullToRefresh_ptrGoogleViewStyle = 14;
			
			// aapt resource value: 1
			public const int PullToRefresh_ptrHeaderBackground = 1;
			
			// aapt resource value: 3
			public const int PullToRefresh_ptrHeaderSubTextColor = 3;
			
			// aapt resource value: 10
			public const int PullToRefresh_ptrHeaderTextAppearance = 10;
			
			// aapt resource value: 2
			public const int PullToRefresh_ptrHeaderTextColor = 2;
			
			// aapt resource value: 30
			public const int PullToRefresh_ptrHideRefeshableViewWhileRefreshingDuration = 30;
			
			// aapt resource value: 27
			public const int PullToRefresh_ptrHideRefeshableViewWhileRefreshingEnabled = 27;
			
			// aapt resource value: 13
			public const int PullToRefresh_ptrIndicatorStyle = 13;
			
			// aapt resource value: 23
			public const int PullToRefresh_ptrListViewExtrasEnabled = 23;
			
			// aapt resource value: 4
			public const int PullToRefresh_ptrMode = 4;
			
			// aapt resource value: 9
			public const int PullToRefresh_ptrOverScroll = 9;
			
			// aapt resource value: 16
			public const int PullToRefresh_ptrPullLabel = 16;
			
			// aapt resource value: 33
			public const int PullToRefresh_ptrRefeshableViewProgressBarOnCenterHeight = 33;
			
			// aapt resource value: 32
			public const int PullToRefresh_ptrRefeshableViewProgressBarOnCenterWidth = 32;
			
			// aapt resource value: 17
			public const int PullToRefresh_ptrRefreshLabel = 17;
			
			// aapt resource value: 0
			public const int PullToRefresh_ptrRefreshableViewBackground = 0;
			
			// aapt resource value: 18
			public const int PullToRefresh_ptrReleaseLabel = 18;
			
			// aapt resource value: 24
			public const int PullToRefresh_ptrRotateDrawableWhilePulling = 24;
			
			// aapt resource value: 22
			public const int PullToRefresh_ptrScrollingWhileRefreshingEnabled = 22;
			
			// aapt resource value: 25
			public const int PullToRefresh_ptrSetGoogleViewLayoutSizeToActionbarHeight = 25;
			
			// aapt resource value: 29
			public const int PullToRefresh_ptrShowGoogleStyleViewAnimationDuration = 29;
			
			// aapt resource value: 26
			public const int PullToRefresh_ptrShowGoogleStyleViewAnimationEnabled = 26;
			
			// aapt resource value: 5
			public const int PullToRefresh_ptrShowIndicator = 5;
			
			// aapt resource value: 20
			public const int PullToRefresh_ptrSmoothScrollDuration = 20;
			
			// aapt resource value: 21
			public const int PullToRefresh_ptrSmoothScrollLongDuration = 21;
			
			// aapt resource value: 11
			public const int PullToRefresh_ptrSubHeaderTextAppearance = 11;
			
			// aapt resource value: 31
			public const int PullToRefresh_ptrViewRefeshableViewProgressBarOnCenterWhileRefreshingDuration = 31;
			
			// aapt resource value: 28
			public const int PullToRefresh_ptrViewRefeshableViewProgressBarOnCenterWhileRefreshingEnabled = 28;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
